version: "3"
services:
  db:
    image: postgres:9.5
  sut:
    build: .
    command: sh /code/test.sh
    depends_on:
      - db
    volumes:
      - .:/code
    environment:
      - CODACY_PROJECT_TOKEN=71ef38b94b90409b9525530ed5500cc3
