# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('copyandpay', '0003_transaction_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='registration_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=46),
            preserve_default=False,
        ),
    ]
