# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyandpay', '0008_userproduct_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ndc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='registration_id',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='result_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
