# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copyandpay', '0010_transaction_initial_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('new', 'new'), ('success', 'success'), ('failed', 'failed')], default='new', max_length=10)),
                ('transaction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='copyandpay.Transaction')),
            ],
        ),
    ]
