# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyandpay', '0011_scheduledpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='user',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='owner_id',
            field=models.CharField(default=0, max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledpayment',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('success', 'success'), ('failed', 'failed'), ('pending', 'pending')], default='new', max_length=10),
        ),
    ]
