# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('copyandpay', '0012_auto_20170929_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproduct',
            name='card',
        ),
        migrations.RemoveField(
            model_name='userproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='scheduledpayment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='initial_transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_product',
        ),
        migrations.AddField(
            model_name='scheduledpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='scheduledpayment',
            name='card',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='copyandpay.CreditCard'),
        ),
        migrations.AddField(
            model_name='scheduledpayment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledpayment',
            name='currency',
            field=models.CharField(default='ZAR', max_length=6),
        ),
        migrations.AddField(
            model_name='scheduledpayment',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scheduledpayment',
            name='run_on_creation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='UserProduct',
        ),
    ]
