# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyandpay', '0013_auto_20171101_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=36, null=True)),
                ('name', models.CharField(blank=True, max_length=36, null=True)),
                ('company', models.CharField(blank=True, max_length=36, null=True)),
                ('mobile', models.CharField(blank=True, max_length=36, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='owner_id',
        ),
        migrations.AlterField(
            model_name='scheduledpayment',
            name='run_on_creation',
            field=models.BooleanField(default=False, help_text="If this is selected, we'll try run this payment immediately"),
        ),
    ]
