# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copyandpay', '0014_auto_20171101_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_transaction', to='copyandpay.Customer'),
        ),
        migrations.AlterField(
            model_name='scheduledpayment',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('processing', 'processing'), ('success', 'success'), ('failed', 'failed'), ('pending', 'pending')], default='new', max_length=10),
        ),
    ]
