# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyandpay', '0016_scheduledpayment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpayment',
            name='is_recurring',
            field=models.BooleanField(default=True, help_text='If true, when transaction successfully completes, it will create another recurring payment 1 month from now'),
        ),
    ]
