# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copyandpay', '0017_scheduledpayment_is_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpayment',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='copyandpay.Product'),
        ),
    ]
